Refactor/model builder
kandidat-highlights/model pull request #9
Opened 2017-03-29 13:34 UTC by Jaxing

This will only change the basic model which we already decided to scrap. I believe that this will make it easier to implement new models as all models will use the same code and we will only have to update on one place.

2017-03-29 22:15 UTC, hsson requested changes
I think this is brilliant. Though it needs to be verified that it actually works. 

Also, for this to be really useful the number of layers should also be a configuration option. Make sure to use the new config template that's been pushed to dev.

2017-03-29 22:15 UTC, hsson commented on model/basic/basic_model.py
> +        if 'use_l2_loss' in config:
With the new template system these checks can be removed as all models will have configurations for everything, even things that won't be used.

2017-03-30 09:02 UTC, Mxiim commented
config.yaml doesn't need to be committed as it is gitignored. Would also like to see an example of how to use ModelBuilder in code, and maybe with added template to config.template.yaml if possible.

2017-03-30 14:50 UTC, hsson approved these changes

2017-03-30 14:51 UTC, hsson commented
Just add new performance measure and tensorboard.

2017-03-31 12:37 UTC, merged